version: "3"

services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/api
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: denhatkemao
    ports:
      - "3307:3306"

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/client
    ports:
      - "3000:3000"

volumes:
  mysql:
