export {default as Home} from './Home';
export {default as Dashboard} from './Dashboard';
export {default as Login} from './Login';
export {default as UserList} from './UserList';
export {default as UserCreate} from './UserCreate';
export {default as Account} from './Account';
export {default as FoodList} from './FoodList';
export {default as FoodCreate} from './FoodCreate';
export {default as FoodUpdate} from './FoodUpdate';
export {Cart} from './Cart';
